import type { UiLanguage } from './index'

type Pack = Record<string, string>
type ExtraLanguage = Exclude<UiLanguage, 'vi' | 'en'>

const ja: Pack = {
  'app.loading':'O-Walletを開いています…','app.shortTagline':'家計管理','common.add':'追加','common.cancel':'キャンセル','common.save':'保存','common.copy':'コピー','common.copied':'コピーしました','common.file':'ファイル','common.all':'すべて','common.other':'その他','common.none':'なし','common.forever':'無期限','common.days':'{count}日','common.on':'オン','common.off':'オフ','common.system':'システム','common.light':'ライト','common.dark':'ダーク','common.connected':'接続済み','common.disconnected':'未接続','common.reconnecting':'再接続中','common.syncing':'同期中…','common.actionRequired':'再接続が必要','common.language':'言語','common.loading':'読み込み中…','common.delete':'削除','common.edit':'編集','common.back':'戻る','common.next':'次へ','common.any':'指定なし',
  'nav.home':'概要','nav.transactions':'取引','nav.analytics':'分析','nav.settings':'設定','nav.addTransaction':'取引を追加','nav.lock':'ロック','nav.sync':'同期','nav.shared':'共有ウォレット',
  'transaction.expense':'支出','transaction.income':'収入','transaction.transfer':'振替','transaction.noDescription':'説明なし',
  'dashboard.title':'概要','dashboard.subtitle':'残高、収入、支出、最近の取引を確認します。','dashboard.balance':'総残高','dashboard.income':'収入','dashboard.expense':'支出','dashboard.net':'差額','dashboard.cashflow':'収支の推移','dashboard.noDataTitle':'データがありません','dashboard.expenseByCategory':'カテゴリ別支出','dashboard.recent':'最近の取引','dashboard.noTransactionsTitle':'取引がありません',
  'analytics.title':'分析','analytics.income':'収入','analytics.expense':'支出','analytics.net':'差額','analytics.cashflow':'キャッシュフロー','analytics.expenseMix':'支出内訳','analytics.noExpenseTitle':'支出なし',
  'transactions.title':'取引','transactions.subtitle':'{count}件の取引','transactions.search':'店舗、メモ、カテゴリを検索…','transactions.allTypes':'すべての種類','transactions.emptyTitle':'一致する取引がありません','transactions.edit':'取引を編集','transactions.duplicate':'取引を複製',
  'modal.title':'取引を追加','modal.editTitle':'取引を編集','modal.amount':'金額','modal.currency':'通貨','modal.time':'日時','modal.category':'カテゴリ','modal.account':'口座','modal.sourceAccount':'振替元口座','modal.destinationAccount':'振替先口座','modal.merchant':'店舗 / 受取人','modal.balanceAfter':'取引後残高','modal.description':'説明 / 振込メッセージ','modal.note':'メモ','modal.tags':'タグ','modal.screenshot':'画像 / レシート','modal.save':'取引を保存','modal.saving':'保存中',
  'settings.title':'設定','settings.subtitle':'同期、表示、セキュリティなどを管理します。','settings.theme':'テーマ','settings.autoSync':'自動同期','settings.imageRetention':'画像の保存期間','settings.security':'セキュリティ','settings.accounts':'口座','settings.categories':'カテゴリ','settings.kindExpense':'支出','settings.kindIncome':'収入','settings.kindBoth':'両方','settings.budgets':'月間予算','settings.chooseCategory':'カテゴリを選択','settings.budgetLimit':'上限','settings.defaultAccount':'新規取引の既定口座','settings.defaultCategory':'新規取引の既定カテゴリ','settings.export':'データを書き出す',
  'accounts.add':'口座を追加','accounts.empty':'口座がありません。','categories.create':'カテゴリを作成','categories.name':'名前','categories.group':'カテゴリグループ','categories.item':'取引カテゴリ','categories.kind':'用途','categories.parent':'所属','categories.root':'最上位','categories.subgroup':'サブグループ','categories.uncategorized':'未分類','categoryPicker.placeholder':'カテゴリを選択','categoryPicker.search':'名前またはパスを検索…',
  'rules.title':'自動化ルール','rules.create':'ルールを作成','rules.empty':'ルールはありません。','rules.name':'ルール名','rules.recipient':'受取人','rules.amount':'金額','rules.category':'カテゴリを選択','rules.account':'口座を選択','rules.add':'ルールを追加',
  'voice.settingsTitle':'音声入力','voice.language':'認識言語','voice.fields':'音声入力の手順','voice.calibration':'音声調整','voice.readSample':'サンプルを読む','voice.listening':'聞き取り中…','voice.entryButton':'音声','voice.entryTitle':'音声入力','voice.listen':'聞き取り開始','voice.listenAgain':'もう一度聞く','voice.apply':'適用','voice.required':'必須','voice.defaultToday':'今日','voice.defaultNow':'現在','voice.emptyOptional':'空欄',
  'sync.prepare':'O-Walletフォルダを準備中…','sync.index':'Google Driveの変更を確認中…','sync.records':'データを更新中…','sync.images':'画像を更新中…','sync.done':'同期が完了しました。',
  'shared.title':'共有ウォレット','shared.refresh':'更新','shared.wallets':'ウォレット','shared.members':'メンバー','shared.addTransaction':'共有取引を追加','shared.income':'収入','shared.expense':'支出','shared.net':'差額'
}

const zhCN: Pack = {
  'app.loading':'正在打开 O-Wallet…','app.shortTagline':'收支管理','common.add':'添加','common.cancel':'取消','common.save':'保存','common.copy':'复制','common.copied':'已复制','common.file':'文件','common.all':'全部','common.other':'其他','common.none':'无','common.forever':'永久','common.days':'{count} 天','common.on':'开启','common.off':'关闭','common.system':'跟随系统','common.light':'浅色','common.dark':'深色','common.connected':'已连接','common.disconnected':'未连接','common.reconnecting':'正在重新连接','common.syncing':'正在同步…','common.actionRequired':'需要重新连接','common.language':'语言','common.loading':'加载中…','common.delete':'删除','common.edit':'编辑','common.back':'返回','common.next':'下一步','common.any':'任意',
  'nav.home':'概览','nav.transactions':'交易','nav.analytics':'分析','nav.settings':'设置','nav.addTransaction':'添加交易','nav.lock':'锁定','nav.sync':'同步','nav.shared':'共享钱包',
  'transaction.expense':'支出','transaction.income':'收入','transaction.transfer':'转账','transaction.noDescription':'无描述',
  'dashboard.title':'概览','dashboard.subtitle':'查看余额、收入、支出和最近交易。','dashboard.balance':'总余额','dashboard.income':'收入','dashboard.expense':'支出','dashboard.net':'净额','dashboard.cashflow':'收支趋势','dashboard.noDataTitle':'暂无数据','dashboard.expenseByCategory':'按类别支出','dashboard.recent':'最近交易','dashboard.noTransactionsTitle':'暂无交易',
  'analytics.title':'分析','analytics.income':'收入','analytics.expense':'支出','analytics.net':'净额','analytics.cashflow':'现金流','analytics.expenseMix':'支出构成','analytics.noExpenseTitle':'暂无支出',
  'transactions.title':'交易','transactions.subtitle':'{count} 笔交易','transactions.search':'搜索商户、备注、类别…','transactions.allTypes':'全部类型','transactions.emptyTitle':'没有匹配的交易','transactions.edit':'编辑交易','transactions.duplicate':'复制交易',
  'modal.title':'添加交易','modal.editTitle':'编辑交易','modal.amount':'金额','modal.currency':'货币','modal.time':'时间','modal.category':'类别','modal.account':'账户','modal.sourceAccount':'转出账户','modal.destinationAccount':'转入账户','modal.merchant':'商户 / 收款人','modal.balanceAfter':'交易后余额','modal.description':'描述 / 转账附言','modal.note':'备注','modal.tags':'标签','modal.screenshot':'截图 / 收据','modal.save':'保存交易','modal.saving':'正在保存',
  'settings.title':'设置','settings.subtitle':'管理同步、外观、安全和其他 O-Wallet 选项。','settings.theme':'主题','settings.autoSync':'自动同步','settings.imageRetention':'图片保留时间','settings.security':'安全','settings.accounts':'账户','settings.categories':'类别','settings.kindExpense':'支出','settings.kindIncome':'收入','settings.kindBoth':'两者','settings.budgets':'月度预算','settings.chooseCategory':'选择类别','settings.budgetLimit':'额度','settings.defaultAccount':'新交易默认账户','settings.defaultCategory':'新交易默认类别','settings.export':'导出数据',
  'accounts.add':'添加账户','accounts.empty':'暂无账户。','categories.create':'创建类别','categories.name':'名称','categories.group':'类别组','categories.item':'交易类别','categories.kind':'用于','categories.parent':'位于','categories.root':'顶层','categories.subgroup':'子组','categories.uncategorized':'未分类','categoryPicker.placeholder':'选择类别','categoryPicker.search':'搜索名称或路径…',
  'rules.title':'自动化规则','rules.create':'创建规则','rules.empty':'暂无规则。','rules.name':'规则名称','rules.recipient':'收款人','rules.amount':'金额','rules.category':'选择类别','rules.account':'选择账户','rules.add':'添加规则',
  'voice.settingsTitle':'语音交易录入','voice.language':'识别语言','voice.fields':'语音输入步骤','voice.calibration':'语音校准','voice.readSample':'朗读示例','voice.listening':'正在聆听…','voice.entryButton':'语音','voice.entryTitle':'语音录入','voice.listen':'开始聆听','voice.listenAgain':'再次聆听','voice.apply':'应用','voice.required':'必填','voice.defaultToday':'今天','voice.defaultNow':'现在','voice.emptyOptional':'留空',
  'sync.prepare':'正在准备 O-Wallet 文件夹…','sync.index':'正在检查 Google Drive 更改…','sync.records':'正在更新数据…','sync.images':'正在更新图片…','sync.done':'同步完成。','shared.title':'共享钱包','shared.refresh':'刷新','shared.wallets':'钱包','shared.members':'成员','shared.addTransaction':'添加共享交易','shared.income':'收入','shared.expense':'支出','shared.net':'净额'
}

const zhTW: Pack = {
  ...zhCN,
  'app.loading':'正在開啟 O-Wallet…','app.shortTagline':'收支管理','common.add':'新增','common.cancel':'取消','common.save':'儲存','common.copy':'複製','common.copied':'已複製','common.file':'檔案','common.all':'全部','common.other':'其他','common.none':'無','common.forever':'永久','common.days':'{count} 天','common.system':'跟隨系統','common.light':'淺色','common.dark':'深色','common.connected':'已連線','common.disconnected':'未連線','common.reconnecting':'正在重新連線','common.syncing':'正在同步…','common.actionRequired':'需要重新連線','common.language':'語言','common.loading':'載入中…','common.delete':'刪除','common.edit':'編輯','common.back':'返回','common.next':'下一步',
  'nav.home':'總覽','nav.transactions':'交易','nav.analytics':'分析','nav.settings':'設定','nav.addTransaction':'新增交易','nav.lock':'鎖定','nav.sync':'同步','nav.shared':'共享錢包','transaction.expense':'支出','transaction.income':'收入','transaction.transfer':'轉帳','dashboard.title':'總覽','dashboard.balance':'總餘額','dashboard.net':'淨額','analytics.title':'分析','transactions.title':'交易','modal.title':'新增交易','modal.editTitle':'編輯交易','modal.amount':'金額','modal.currency':'幣別','modal.category':'分類','modal.account':'帳戶','modal.sourceAccount':'轉出帳戶','modal.destinationAccount':'轉入帳戶','modal.merchant':'商家 / 收款人','modal.balanceAfter':'交易後餘額','modal.note':'備註','modal.tags':'標籤','modal.screenshot':'截圖 / 收據','modal.save':'儲存交易','settings.title':'設定','settings.accounts':'帳戶','settings.categories':'分類','settings.budgets':'每月預算','settings.export':'匯出資料','accounts.add':'新增帳戶','categories.create':'建立分類','categories.group':'分類群組','categories.item':'交易分類','categories.uncategorized':'未分類','categoryPicker.placeholder':'選擇分類','rules.title':'自動化規則','rules.create':'建立規則','voice.entryTitle':'語音輸入','voice.listen':'開始聆聽','sync.done':'同步完成。','shared.title':'共享錢包'
}

const th: Pack = {
  'app.loading':'กำลังเปิด O-Wallet…','app.shortTagline':'จัดการรายรับรายจ่าย','common.add':'เพิ่ม','common.cancel':'ยกเลิก','common.save':'บันทึก','common.copy':'คัดลอก','common.copied':'คัดลอกแล้ว','common.file':'ไฟล์','common.all':'ทั้งหมด','common.other':'อื่นๆ','common.none':'ไม่มี','common.forever':'ตลอดไป','common.days':'{count} วัน','common.on':'เปิด','common.off':'ปิด','common.system':'ตามระบบ','common.light':'สว่าง','common.dark':'มืด','common.connected':'เชื่อมต่อแล้ว','common.disconnected':'ยังไม่เชื่อมต่อ','common.reconnecting':'กำลังเชื่อมต่อใหม่','common.syncing':'กำลังซิงค์…','common.language':'ภาษา','common.loading':'กำลังโหลด…','common.delete':'ลบ','common.edit':'แก้ไข','common.back':'กลับ','common.next':'ถัดไป','common.any':'ใดๆ',
  'nav.home':'ภาพรวม','nav.transactions':'รายการ','nav.analytics':'วิเคราะห์','nav.settings':'ตั้งค่า','nav.addTransaction':'เพิ่มรายการ','nav.lock':'ล็อก','nav.sync':'ซิงค์','nav.shared':'กระเป๋าแชร์','transaction.expense':'รายจ่าย','transaction.income':'รายรับ','transaction.transfer':'โอน','dashboard.title':'ภาพรวม','dashboard.balance':'ยอดคงเหลือรวม','dashboard.income':'รายรับ','dashboard.expense':'รายจ่าย','dashboard.net':'สุทธิ','dashboard.cashflow':'กระแสเงินสด','dashboard.recent':'รายการล่าสุด','analytics.title':'วิเคราะห์','analytics.income':'รายรับ','analytics.expense':'รายจ่าย','analytics.net':'สุทธิ','analytics.cashflow':'กระแสเงินสด','transactions.title':'รายการ','transactions.subtitle':'{count} รายการ','transactions.search':'ค้นหาร้านค้า โน้ต หมวดหมู่…','transactions.edit':'แก้ไขรายการ','modal.title':'เพิ่มรายการ','modal.editTitle':'แก้ไขรายการ','modal.amount':'จำนวนเงิน','modal.currency':'สกุลเงิน','modal.time':'เวลา','modal.category':'หมวดหมู่','modal.account':'บัญชี','modal.sourceAccount':'บัญชีต้นทาง','modal.destinationAccount':'บัญชีปลายทาง','modal.merchant':'ร้านค้า / ผู้รับ','modal.balanceAfter':'ยอดหลังรายการ','modal.description':'รายละเอียด','modal.note':'โน้ต','modal.tags':'แท็ก','modal.screenshot':'ภาพ / ใบเสร็จ','modal.save':'บันทึกรายการ','settings.title':'ตั้งค่า','settings.theme':'ธีม','settings.accounts':'บัญชี','settings.categories':'หมวดหมู่','settings.budgets':'งบประมาณรายเดือน','settings.security':'ความปลอดภัย','settings.export':'ส่งออกข้อมูล','accounts.add':'เพิ่มบัญชี','categories.create':'สร้างหมวดหมู่','categories.group':'กลุ่มหมวดหมู่','categories.item':'หมวดหมู่รายการ','categories.uncategorized':'ไม่จัดหมวดหมู่','categoryPicker.placeholder':'เลือกหมวดหมู่','rules.title':'กฎอัตโนมัติ','rules.create':'สร้างกฎ','voice.settingsTitle':'ป้อนรายการด้วยเสียง','voice.language':'ภาษาการรู้จำ','voice.entryTitle':'ป้อนด้วยเสียง','voice.listen':'เริ่มฟัง','voice.apply':'นำไปใช้','sync.done':'ซิงค์เสร็จแล้ว','shared.title':'กระเป๋าแชร์','shared.members':'สมาชิก'
}

const id: Pack = {
  'app.loading':'Membuka O-Wallet…','app.shortTagline':'Pengelola pemasukan dan pengeluaran','common.add':'Tambah','common.cancel':'Batal','common.save':'Simpan','common.copy':'Salin','common.copied':'Disalin','common.file':'Berkas','common.all':'Semua','common.other':'Lainnya','common.none':'Tidak ada','common.forever':'Selamanya','common.days':'{count} hari','common.on':'Aktif','common.off':'Nonaktif','common.system':'Sistem','common.light':'Terang','common.dark':'Gelap','common.connected':'Terhubung','common.disconnected':'Tidak terhubung','common.reconnecting':'Menghubungkan ulang','common.syncing':'Menyinkronkan…','common.language':'Bahasa','common.loading':'Memuat…','common.delete':'Hapus','common.edit':'Edit','common.back':'Kembali','common.next':'Berikutnya','common.any':'Apa saja',
  'nav.home':'Ringkasan','nav.transactions':'Transaksi','nav.analytics':'Analitik','nav.settings':'Pengaturan','nav.addTransaction':'Tambah transaksi','nav.lock':'Kunci','nav.sync':'Sinkronkan','nav.shared':'Dompet bersama','transaction.expense':'Pengeluaran','transaction.income':'Pemasukan','transaction.transfer':'Transfer','dashboard.title':'Ringkasan','dashboard.balance':'Total saldo','dashboard.income':'Pemasukan','dashboard.expense':'Pengeluaran','dashboard.net':'Bersih','dashboard.cashflow':'Arus kas','dashboard.recent':'Transaksi terbaru','analytics.title':'Analitik','analytics.income':'Pemasukan','analytics.expense':'Pengeluaran','analytics.net':'Bersih','analytics.cashflow':'Arus kas','transactions.title':'Transaksi','transactions.subtitle':'{count} transaksi','transactions.search':'Cari merchant, catatan, kategori…','transactions.edit':'Edit transaksi','modal.title':'Tambah transaksi','modal.editTitle':'Edit transaksi','modal.amount':'Jumlah','modal.currency':'Mata uang','modal.time':'Waktu','modal.category':'Kategori','modal.account':'Akun','modal.sourceAccount':'Akun sumber','modal.destinationAccount':'Akun tujuan','modal.merchant':'Merchant / penerima','modal.balanceAfter':'Saldo setelah transaksi','modal.description':'Deskripsi','modal.note':'Catatan','modal.tags':'Tag','modal.screenshot':'Gambar / struk','modal.save':'Simpan transaksi','settings.title':'Pengaturan','settings.theme':'Tema','settings.accounts':'Akun','settings.categories':'Kategori','settings.budgets':'Anggaran bulanan','settings.security':'Keamanan','settings.export':'Ekspor data','accounts.add':'Tambah akun','categories.create':'Buat kategori','categories.group':'Grup kategori','categories.item':'Kategori transaksi','categories.uncategorized':'Tanpa kategori','categoryPicker.placeholder':'Pilih kategori','rules.title':'Aturan otomatis','rules.create':'Buat aturan','voice.settingsTitle':'Input transaksi suara','voice.language':'Bahasa pengenalan','voice.entryTitle':'Input suara','voice.listen':'Mulai mendengarkan','voice.apply':'Terapkan','sync.done':'Sinkronisasi selesai.','shared.title':'Dompet bersama','shared.members':'Anggota'
}

const es: Pack = {
  'app.loading':'Abriendo O-Wallet…','app.shortTagline':'Control de ingresos y gastos','common.add':'Añadir','common.cancel':'Cancelar','common.save':'Guardar','common.copy':'Copiar','common.copied':'Copiado','common.file':'Archivo','common.all':'Todo','common.other':'Otro','common.none':'Ninguno','common.forever':'Siempre','common.days':'{count} días','common.on':'Activado','common.off':'Desactivado','common.system':'Sistema','common.light':'Claro','common.dark':'Oscuro','common.connected':'Conectado','common.disconnected':'Desconectado','common.reconnecting':'Reconectando','common.syncing':'Sincronizando…','common.language':'Idioma','common.loading':'Cargando…','common.delete':'Eliminar','common.edit':'Editar','common.back':'Atrás','common.next':'Siguiente','common.any':'Cualquiera',
  'nav.home':'Resumen','nav.transactions':'Transacciones','nav.analytics':'Análisis','nav.settings':'Ajustes','nav.addTransaction':'Añadir transacción','nav.lock':'Bloquear','nav.sync':'Sincronizar','nav.shared':'Carteras compartidas','transaction.expense':'Gasto','transaction.income':'Ingreso','transaction.transfer':'Transferencia','dashboard.title':'Resumen','dashboard.balance':'Saldo total','dashboard.income':'Ingresos','dashboard.expense':'Gastos','dashboard.net':'Neto','dashboard.cashflow':'Flujo de caja','dashboard.recent':'Transacciones recientes','analytics.title':'Análisis','analytics.income':'Ingresos','analytics.expense':'Gastos','analytics.net':'Neto','analytics.cashflow':'Flujo de caja','transactions.title':'Transacciones','transactions.subtitle':'{count} transacciones','transactions.search':'Buscar comercio, nota, categoría…','transactions.edit':'Editar transacción','modal.title':'Añadir transacción','modal.editTitle':'Editar transacción','modal.amount':'Importe','modal.currency':'Moneda','modal.time':'Fecha y hora','modal.category':'Categoría','modal.account':'Cuenta','modal.sourceAccount':'Cuenta de origen','modal.destinationAccount':'Cuenta de destino','modal.merchant':'Comercio / destinatario','modal.balanceAfter':'Saldo después de la transacción','modal.description':'Descripción','modal.note':'Nota','modal.tags':'Etiquetas','modal.screenshot':'Imagen / recibo','modal.save':'Guardar transacción','settings.title':'Ajustes','settings.theme':'Tema','settings.accounts':'Cuentas','settings.categories':'Categorías','settings.budgets':'Presupuestos mensuales','settings.security':'Seguridad','settings.export':'Exportar datos','accounts.add':'Añadir cuenta','categories.create':'Crear categoría','categories.group':'Grupo de categorías','categories.item':'Categoría de transacción','categories.uncategorized':'Sin categoría','categoryPicker.placeholder':'Elegir categoría','rules.title':'Reglas de automatización','rules.create':'Crear regla','voice.settingsTitle':'Entrada por voz','voice.language':'Idioma de reconocimiento','voice.entryTitle':'Entrada por voz','voice.listen':'Empezar a escuchar','voice.apply':'Aplicar','sync.done':'Sincronización completada.','shared.title':'Carteras compartidas','shared.members':'Miembros'
}

const fr: Pack = {
  'app.loading':'Ouverture de O-Wallet…','app.shortTagline':'Suivi des revenus et dépenses','common.add':'Ajouter','common.cancel':'Annuler','common.save':'Enregistrer','common.copy':'Copier','common.copied':'Copié','common.file':'Fichier','common.all':'Tout','common.other':'Autre','common.none':'Aucun','common.forever':'Toujours','common.days':'{count} jours','common.on':'Activé','common.off':'Désactivé','common.system':'Système','common.light':'Clair','common.dark':'Sombre','common.connected':'Connecté','common.disconnected':'Déconnecté','common.reconnecting':'Reconnexion','common.syncing':'Synchronisation…','common.language':'Langue','common.loading':'Chargement…','common.delete':'Supprimer','common.edit':'Modifier','common.back':'Retour','common.next':'Suivant','common.any':'Tous',
  'nav.home':'Aperçu','nav.transactions':'Transactions','nav.analytics':'Analyses','nav.settings':'Paramètres','nav.addTransaction':'Ajouter une transaction','nav.lock':'Verrouiller','nav.sync':'Synchroniser','nav.shared':'Portefeuilles partagés','transaction.expense':'Dépense','transaction.income':'Revenu','transaction.transfer':'Virement','dashboard.title':'Aperçu','dashboard.balance':'Solde total','dashboard.income':'Revenus','dashboard.expense':'Dépenses','dashboard.net':'Net','dashboard.cashflow':'Flux de trésorerie','dashboard.recent':'Transactions récentes','analytics.title':'Analyses','analytics.income':'Revenus','analytics.expense':'Dépenses','analytics.net':'Net','analytics.cashflow':'Flux de trésorerie','transactions.title':'Transactions','transactions.subtitle':'{count} transactions','transactions.search':'Rechercher commerçant, note, catégorie…','transactions.edit':'Modifier la transaction','modal.title':'Ajouter une transaction','modal.editTitle':'Modifier la transaction','modal.amount':'Montant','modal.currency':'Devise','modal.time':'Date et heure','modal.category':'Catégorie','modal.account':'Compte','modal.sourceAccount':'Compte source','modal.destinationAccount':'Compte destination','modal.merchant':'Commerçant / destinataire','modal.balanceAfter':'Solde après transaction','modal.description':'Description','modal.note':'Note','modal.tags':'Étiquettes','modal.screenshot':'Image / reçu','modal.save':'Enregistrer la transaction','settings.title':'Paramètres','settings.theme':'Thème','settings.accounts':'Comptes','settings.categories':'Catégories','settings.budgets':'Budgets mensuels','settings.security':'Sécurité','settings.export':'Exporter les données','accounts.add':'Ajouter un compte','categories.create':'Créer une catégorie','categories.group':'Groupe de catégories','categories.item':'Catégorie de transaction','categories.uncategorized':'Non classé','categoryPicker.placeholder':'Choisir une catégorie','rules.title':'Règles d’automatisation','rules.create':'Créer une règle','voice.settingsTitle':'Saisie vocale','voice.language':'Langue de reconnaissance','voice.entryTitle':'Saisie vocale','voice.listen':'Commencer l’écoute','voice.apply':'Appliquer','sync.done':'Synchronisation terminée.','shared.title':'Portefeuilles partagés','shared.members':'Membres'
}

const de: Pack = {
  'app.loading':'O-Wallet wird geöffnet…','app.shortTagline':'Einnahmen und Ausgaben verwalten','common.add':'Hinzufügen','common.cancel':'Abbrechen','common.save':'Speichern','common.copy':'Kopieren','common.copied':'Kopiert','common.file':'Datei','common.all':'Alle','common.other':'Sonstiges','common.none':'Keine','common.forever':'Unbegrenzt','common.days':'{count} Tage','common.on':'Ein','common.off':'Aus','common.system':'System','common.light':'Hell','common.dark':'Dunkel','common.connected':'Verbunden','common.disconnected':'Nicht verbunden','common.reconnecting':'Verbindung wird wiederhergestellt','common.syncing':'Synchronisierung…','common.language':'Sprache','common.loading':'Laden…','common.delete':'Löschen','common.edit':'Bearbeiten','common.back':'Zurück','common.next':'Weiter','common.any':'Beliebig',
  'nav.home':'Übersicht','nav.transactions':'Transaktionen','nav.analytics':'Analyse','nav.settings':'Einstellungen','nav.addTransaction':'Transaktion hinzufügen','nav.lock':'Sperren','nav.sync':'Synchronisieren','nav.shared':'Geteilte Wallets','transaction.expense':'Ausgabe','transaction.income':'Einnahme','transaction.transfer':'Überweisung','dashboard.title':'Übersicht','dashboard.balance':'Gesamtsaldo','dashboard.income':'Einnahmen','dashboard.expense':'Ausgaben','dashboard.net':'Netto','dashboard.cashflow':'Cashflow','dashboard.recent':'Letzte Transaktionen','analytics.title':'Analyse','analytics.income':'Einnahmen','analytics.expense':'Ausgaben','analytics.net':'Netto','analytics.cashflow':'Cashflow','transactions.title':'Transaktionen','transactions.subtitle':'{count} Transaktionen','transactions.search':'Händler, Notiz, Kategorie suchen…','transactions.edit':'Transaktion bearbeiten','modal.title':'Transaktion hinzufügen','modal.editTitle':'Transaktion bearbeiten','modal.amount':'Betrag','modal.currency':'Währung','modal.time':'Datum und Uhrzeit','modal.category':'Kategorie','modal.account':'Konto','modal.sourceAccount':'Quellkonto','modal.destinationAccount':'Zielkonto','modal.merchant':'Händler / Empfänger','modal.balanceAfter':'Saldo nach Transaktion','modal.description':'Beschreibung','modal.note':'Notiz','modal.tags':'Tags','modal.screenshot':'Bild / Beleg','modal.save':'Transaktion speichern','settings.title':'Einstellungen','settings.theme':'Design','settings.accounts':'Konten','settings.categories':'Kategorien','settings.budgets':'Monatsbudgets','settings.security':'Sicherheit','settings.export':'Daten exportieren','accounts.add':'Konto hinzufügen','categories.create':'Kategorie erstellen','categories.group':'Kategoriegruppe','categories.item':'Transaktionskategorie','categories.uncategorized':'Nicht kategorisiert','categoryPicker.placeholder':'Kategorie auswählen','rules.title':'Automatisierungsregeln','rules.create':'Regel erstellen','voice.settingsTitle':'Spracheingabe','voice.language':'Erkennungssprache','voice.entryTitle':'Spracheingabe','voice.listen':'Zuhören starten','voice.apply':'Übernehmen','sync.done':'Synchronisierung abgeschlossen.','shared.title':'Geteilte Wallets','shared.members':'Mitglieder'
}

const ptBR: Pack = {
  'app.loading':'Abrindo o O-Wallet…','app.shortTagline':'Controle de receitas e despesas','common.add':'Adicionar','common.cancel':'Cancelar','common.save':'Salvar','common.copy':'Copiar','common.copied':'Copiado','common.file':'Arquivo','common.all':'Todos','common.other':'Outro','common.none':'Nenhum','common.forever':'Para sempre','common.days':'{count} dias','common.on':'Ligado','common.off':'Desligado','common.system':'Sistema','common.light':'Claro','common.dark':'Escuro','common.connected':'Conectado','common.disconnected':'Desconectado','common.reconnecting':'Reconectando','common.syncing':'Sincronizando…','common.language':'Idioma','common.loading':'Carregando…','common.delete':'Excluir','common.edit':'Editar','common.back':'Voltar','common.next':'Próximo','common.any':'Qualquer',
  'nav.home':'Visão geral','nav.transactions':'Transações','nav.analytics':'Análises','nav.settings':'Configurações','nav.addTransaction':'Adicionar transação','nav.lock':'Bloquear','nav.sync':'Sincronizar','nav.shared':'Carteiras compartilhadas','transaction.expense':'Despesa','transaction.income':'Receita','transaction.transfer':'Transferência','dashboard.title':'Visão geral','dashboard.balance':'Saldo total','dashboard.income':'Receitas','dashboard.expense':'Despesas','dashboard.net':'Líquido','dashboard.cashflow':'Fluxo de caixa','dashboard.recent':'Transações recentes','analytics.title':'Análises','analytics.income':'Receitas','analytics.expense':'Despesas','analytics.net':'Líquido','analytics.cashflow':'Fluxo de caixa','transactions.title':'Transações','transactions.subtitle':'{count} transações','transactions.search':'Buscar estabelecimento, nota, categoria…','transactions.edit':'Editar transação','modal.title':'Adicionar transação','modal.editTitle':'Editar transação','modal.amount':'Valor','modal.currency':'Moeda','modal.time':'Data e hora','modal.category':'Categoria','modal.account':'Conta','modal.sourceAccount':'Conta de origem','modal.destinationAccount':'Conta de destino','modal.merchant':'Estabelecimento / destinatário','modal.balanceAfter':'Saldo após a transação','modal.description':'Descrição','modal.note':'Nota','modal.tags':'Tags','modal.screenshot':'Imagem / recibo','modal.save':'Salvar transação','settings.title':'Configurações','settings.theme':'Tema','settings.accounts':'Contas','settings.categories':'Categorias','settings.budgets':'Orçamentos mensais','settings.security':'Segurança','settings.export':'Exportar dados','accounts.add':'Adicionar conta','categories.create':'Criar categoria','categories.group':'Grupo de categorias','categories.item':'Categoria de transação','categories.uncategorized':'Sem categoria','categoryPicker.placeholder':'Escolher categoria','rules.title':'Regras de automação','rules.create':'Criar regra','voice.settingsTitle':'Entrada por voz','voice.language':'Idioma de reconhecimento','voice.entryTitle':'Entrada por voz','voice.listen':'Começar a ouvir','voice.apply':'Aplicar','sync.done':'Sincronização concluída.','shared.title':'Carteiras compartilhadas','shared.members':'Membros'
}

const ru: Pack = {
  'app.loading':'Открываем O-Wallet…','app.shortTagline':'Учёт доходов и расходов','common.add':'Добавить','common.cancel':'Отмена','common.save':'Сохранить','common.copy':'Копировать','common.copied':'Скопировано','common.file':'Файл','common.all':'Все','common.other':'Другое','common.none':'Нет','common.forever':'Навсегда','common.days':'{count} дн.','common.on':'Вкл.','common.off':'Выкл.','common.system':'Системная','common.light':'Светлая','common.dark':'Тёмная','common.connected':'Подключено','common.disconnected':'Не подключено','common.reconnecting':'Повторное подключение','common.syncing':'Синхронизация…','common.language':'Язык','common.loading':'Загрузка…','common.delete':'Удалить','common.edit':'Изменить','common.back':'Назад','common.next':'Далее','common.any':'Любой',
  'nav.home':'Обзор','nav.transactions':'Транзакции','nav.analytics':'Аналитика','nav.settings':'Настройки','nav.addTransaction':'Добавить транзакцию','nav.lock':'Заблокировать','nav.sync':'Синхронизировать','nav.shared':'Общие кошельки','transaction.expense':'Расход','transaction.income':'Доход','transaction.transfer':'Перевод','dashboard.title':'Обзор','dashboard.balance':'Общий баланс','dashboard.income':'Доходы','dashboard.expense':'Расходы','dashboard.net':'Итого','dashboard.cashflow':'Денежный поток','dashboard.recent':'Последние транзакции','analytics.title':'Аналитика','analytics.income':'Доходы','analytics.expense':'Расходы','analytics.net':'Итого','analytics.cashflow':'Денежный поток','transactions.title':'Транзакции','transactions.subtitle':'Транзакций: {count}','transactions.search':'Поиск по магазину, заметке, категории…','transactions.edit':'Изменить транзакцию','modal.title':'Добавить транзакцию','modal.editTitle':'Изменить транзакцию','modal.amount':'Сумма','modal.currency':'Валюта','modal.time':'Дата и время','modal.category':'Категория','modal.account':'Счёт','modal.sourceAccount':'Счёт-источник','modal.destinationAccount':'Счёт назначения','modal.merchant':'Магазин / получатель','modal.balanceAfter':'Баланс после транзакции','modal.description':'Описание','modal.note':'Заметка','modal.tags':'Теги','modal.screenshot':'Изображение / чек','modal.save':'Сохранить транзакцию','settings.title':'Настройки','settings.theme':'Тема','settings.accounts':'Счета','settings.categories':'Категории','settings.budgets':'Месячные бюджеты','settings.security':'Безопасность','settings.export':'Экспорт данных','accounts.add':'Добавить счёт','categories.create':'Создать категорию','categories.group':'Группа категорий','categories.item':'Категория транзакции','categories.uncategorized':'Без категории','categoryPicker.placeholder':'Выбрать категорию','rules.title':'Правила автоматизации','rules.create':'Создать правило','voice.settingsTitle':'Голосовой ввод','voice.language':'Язык распознавания','voice.entryTitle':'Голосовой ввод','voice.listen':'Начать слушать','voice.apply':'Применить','sync.done':'Синхронизация завершена.','shared.title':'Общие кошельки','shared.members':'Участники'
}

export const TRANSLATION_PACKS: Record<ExtraLanguage, Pack> = {
  ja,
  'zh-CN': zhCN,
  'zh-TW': zhTW,
  th,
  id,
  es,
  fr,
  de,
  'pt-BR': ptBR,
  ru,
}
