import { useEffect, useState, type ReactNode } from 'react'
import { Cloud, Database, Download, ExternalLink, FolderOpen, LockKeyhole, Plus, RefreshCw, Settings2, ShieldCheck, Sparkles, Trash2, Unplug, WalletCards } from 'lucide-react'
import { useWallet } from '../WalletContext'
import { accountDisplayName, UI_LANGUAGES, useI18n, type UiLanguage } from '../i18n'
import { categoryPath, selectableCategories } from '../lib/categories'
import { bytesToHuman, formatMoney } from '../lib/format'
import { findExistingDriveLayout, openDriveFolderUrl } from '../lib/drive'
import { openTrustedExternalUrl, safeGoogleProfileImageUrl } from '../lib/security'
import type { AppSettings, BudgetConfig, RememberDuration, ThemeMode, VaultRememberDuration } from '../types'
import { ExternalImport } from './ExternalImport'
import { AccountManager } from './AccountManager'
import { AiSettings } from './AiSettings'
import { VoiceSettings } from './VoiceSettings'
import { CategoryManager } from './CategoryManager'
import { RuleManager } from './RuleManager'
import { CategoryPicker } from './CategoryPicker'
import { AccountSelect } from './AccountSelect'
import { CurrencyPicker } from './CurrencyPicker'
import { QuickUnlockSettings } from './QuickUnlockSettings'
import { PersonalCloudSettings } from './PersonalCloudSettings'
import { Badge, Button, Card, Input, Label, Select } from './ui'

type SettingsSection = 'general' | 'wallet' | 'input' | 'sync' | 'cloud' | 'data'
type WalletSection = 'defaults' | 'accounts' | 'categories' | 'budgets' | 'rules'
type InputSection = 'voice' | 'ocr' | 'ai'

type SettingsCopy = {
  general:string; generalHint:string; wallet:string; walletHint:string; input:string; inputHint:string; sync:string; syncHint:string; cloud:string; cloudHint:string; data:string; dataHint:string
  defaults:string; accounts:string; categories:string; budgets:string; rules:string; voice:string; ocr:string; ai:string
  generalTitle:string; generalText:string; walletTitle:string; walletText:string; inputTitle:string; inputText:string; syncTitle:string; syncText:string; dataTitle:string; dataText:string
  budgetTitle:string; budgetHint:string; reportingCurrency:string; reportingCurrencyHint:string; addBudget:string; noBudgets:string
}

const COPY: Record<UiLanguage, SettingsCopy> = {
  vi: {
    general:'Chung', generalHint:'Giao diện và cách ứng dụng hoạt động', wallet:'Ví cá nhân', walletHint:'Tài khoản, pocket và danh mục', input:'Nhập liệu & AI', inputHint:'Voice, OCR và AI', sync:'Đồng bộ & bảo mật', syncHint:'Google Drive, Quick Unlock và khóa ví', cloud:'Personal Cloud', cloudHint:'Cloudflare Worker của riêng bạn', data:'Dữ liệu & ứng dụng', dataHint:'Nhập, xuất, dung lượng và thông tin app',
    defaults:'Mặc định', accounts:'Tài khoản', categories:'Danh mục', budgets:'Ngân sách', rules:'Quy tắc', voice:'Giọng nói', ocr:'OCR', ai:'AI',
    generalTitle:'Thiết lập chung', generalText:'Các tùy chọn về giao diện và cách O-Wallet hoạt động trên thiết bị này.', walletTitle:'Thiết lập ví cá nhân', walletText:'Tiền tệ của giao dịch lấy từ pocket của tài khoản; tiền tệ báo cáo chỉ dùng cho chế độ quy đổi.', inputTitle:'Nhập liệu & tự động hóa', inputText:'Cấu hình các cách nhập giao dịch hằng ngày.', syncTitle:'Đồng bộ & bảo mật', syncText:'Quản lý Google Drive, Quick Unlock, ghi nhớ phiên, khóa ví và đổi tài khoản.', dataTitle:'Dữ liệu & ứng dụng', dataText:'Nhập hoặc xuất dữ liệu, kiểm tra dung lượng local và thông tin ứng dụng.',
    budgetTitle:'Ngân sách / mục tiêu chi tiêu', budgetHint:'Đây là ngưỡng theo dõi theo tháng, không phải hạn mức cứng. O-Wallet vẫn ghi giao dịch khi vượt ngân sách.', reportingCurrency:'Tiền tệ quy đổi / báo cáo', reportingCurrencyHint:'Chỉ dùng cho Dashboard, Analytics và ngân sách ở chế độ quy đổi. Giao dịch luôn giữ số tiền và tiền tệ gốc theo account pocket.', addBudget:'Thêm ngân sách', noBudgets:'Chưa có ngân sách nào.'
  },
  en: {
    general:'General', generalHint:'Appearance and app behavior', wallet:'Personal wallet', walletHint:'Accounts, currency pockets and categories', input:'Input & AI', inputHint:'Voice, OCR and AI', sync:'Sync & security', syncHint:'Google Drive, Quick Unlock and locking', cloud:'Personal Cloud', cloudHint:'Your own Cloudflare Worker', data:'Data & app', dataHint:'Import, export, storage and app info',
    defaults:'Defaults', accounts:'Accounts', categories:'Categories', budgets:'Budgets', rules:'Rules', voice:'Voice', ocr:'OCR', ai:'AI',
    generalTitle:'General settings', generalText:'Options that affect appearance and how O-Wallet behaves on this device.', walletTitle:'Personal wallet settings', walletText:'Transaction currency comes from the account pocket; the reporting currency is only used for converted views.', inputTitle:'Input & automation', inputText:'Configure the ways you record everyday transactions.', syncTitle:'Sync & security', syncText:'Manage Google Drive, Quick Unlock, session retention, locking and account switching.', dataTitle:'Data & app', dataText:'Import or export data, inspect local storage and view app information.',
    budgetTitle:'Budget / spending target', budgetHint:'This is a monthly tracking target, not a hard spending limit. O-Wallet still records transactions after you exceed it.', reportingCurrency:'Conversion / reporting currency', reportingCurrencyHint:'Used by converted Dashboard, Analytics and budget views only. Transactions always keep their original account-pocket amount and currency.', addBudget:'Add budget', noBudgets:'No budgets yet.'
  },
  ja: {
    general:'一般', generalHint:'表示とアプリの動作', wallet:'個人ウォレット', walletHint:'口座・通貨・カテゴリ', input:'入力・AI', inputHint:'音声入力、OCR、AI', sync:'同期・セキュリティ', syncHint:'Google Drive、Quick Unlock、ロック', cloud:'Personal Cloud', cloudHint:'自分専用の Cloudflare Worker', data:'データ・アプリ', dataHint:'インポート、書き出し、保存容量、アプリ情報',
    defaults:'既定値', accounts:'口座', categories:'カテゴリ', budgets:'予算', rules:'ルール', voice:'音声入力', ocr:'OCR', ai:'AI',
    generalTitle:'一般設定', generalText:'この端末での表示や O-Wallet の動作を設定します。', walletTitle:'個人ウォレット設定', walletText:'取引通貨は口座の通貨ポケットから決まり、集計通貨は換算表示にのみ使用します。', inputTitle:'入力・自動化', inputText:'日々の取引を入力する方法を設定します。', syncTitle:'同期・セキュリティ', syncText:'Google Drive、Quick Unlock、セッション保持、ロック、アカウント切り替えを管理します。', dataTitle:'データ・アプリ', dataText:'データのインポート／書き出し、端末内の使用量、アプリ情報を確認できます。',
    budgetTitle:'予算 / 支出目標', budgetHint:'月ごとの目安です。利用上限ではないため、超過後も取引は記録されます。', reportingCurrency:'換算・集計通貨', reportingCurrencyHint:'換算表示の Dashboard、Analytics、予算でのみ使用します。各取引の元の金額と通貨は保持されます。', addBudget:'予算を追加', noBudgets:'予算はまだありません。'
  },
  'zh-CN': {
    general:'通用', generalHint:'外观与应用行为', wallet:'个人钱包', walletHint:'账户、币种余额和类别', input:'录入与 AI', inputHint:'语音、OCR 与 AI', sync:'同步与安全', syncHint:'Google Drive、Quick Unlock 与锁定', cloud:'Personal Cloud', cloudHint:'你自己的 Cloudflare Worker', data:'数据与应用', dataHint:'导入、导出、存储与应用信息',
    defaults:'默认值', accounts:'账户', categories:'类别', budgets:'预算', rules:'规则', voice:'语音', ocr:'OCR', ai:'AI',
    generalTitle:'通用设置', generalText:'设置此设备上的界面与 O-Wallet 行为。', walletTitle:'个人钱包设置', walletText:'交易币种由账户中的币种余额决定；报告币种仅用于换算视图。', inputTitle:'录入与自动化', inputText:'配置日常记录交易的方式。', syncTitle:'同步与安全', syncText:'管理 Google Drive、Quick Unlock、会话保留、锁定和账户切换。', dataTitle:'数据与应用', dataText:'导入或导出数据、查看本地存储占用和应用信息。',
    budgetTitle:'预算 / 支出目标', budgetHint:'这是按月跟踪的目标，不是强制限额。超过后 O-Wallet 仍会正常记录交易。', reportingCurrency:'换算 / 报告币种', reportingCurrencyHint:'仅用于换算后的 Dashboard、Analytics 和预算视图。交易始终保留原始金额与币种。', addBudget:'添加预算', noBudgets:'暂未设置预算。'
  },
  'zh-TW': {
    general:'一般', generalHint:'外觀與應用程式行為', wallet:'個人錢包', walletHint:'帳戶、幣別餘額與分類', input:'輸入與 AI', inputHint:'語音、OCR 與 AI', sync:'同步與安全性', syncHint:'Google Drive、Quick Unlock 與鎖定', cloud:'Personal Cloud', cloudHint:'你自己的 Cloudflare Worker', data:'資料與應用程式', dataHint:'匯入、匯出、儲存空間與應用程式資訊',
    defaults:'預設值', accounts:'帳戶', categories:'分類', budgets:'預算', rules:'規則', voice:'語音', ocr:'OCR', ai:'AI',
    generalTitle:'一般設定', generalText:'設定此裝置上的介面與 O-Wallet 行為。', walletTitle:'個人錢包設定', walletText:'交易幣別由帳戶中的幣別餘額決定；報告幣別只用於換算檢視。', inputTitle:'輸入與自動化', inputText:'設定日常記錄交易的方式。', syncTitle:'同步與安全性', syncText:'管理 Google Drive、Quick Unlock、工作階段保留、鎖定與帳戶切換。', dataTitle:'資料與應用程式', dataText:'匯入或匯出資料、查看本機儲存空間與應用程式資訊。',
    budgetTitle:'預算 / 支出目標', budgetHint:'這是每月追蹤目標，不是強制上限。超過後 O-Wallet 仍會正常記錄交易。', reportingCurrency:'換算 / 報告幣別', reportingCurrencyHint:'只用於換算後的 Dashboard、Analytics 與預算檢視。交易會保留原始金額與幣別。', addBudget:'新增預算', noBudgets:'尚未設定預算。'
  },
  th: {
    general:'ทั่วไป', generalHint:'หน้าตาและการทำงานของแอป', wallet:'กระเป๋าส่วนตัว', walletHint:'บัญชี สกุลเงิน และหมวดหมู่', input:'การป้อนข้อมูลและ AI', inputHint:'เสียง OCR และ AI', sync:'ซิงค์และความปลอดภัย', syncHint:'Google Drive, Quick Unlock และการล็อก', cloud:'Personal Cloud', cloudHint:'Cloudflare Worker ส่วนตัวของคุณ', data:'ข้อมูลและแอป', dataHint:'นำเข้า ส่งออก พื้นที่จัดเก็บ และข้อมูลแอป',
    defaults:'ค่าเริ่มต้น', accounts:'บัญชี', categories:'หมวดหมู่', budgets:'งบประมาณ', rules:'กฎ', voice:'เสียง', ocr:'OCR', ai:'AI',
    generalTitle:'การตั้งค่าทั่วไป', generalText:'ตั้งค่าหน้าตาและการทำงานของ O-Wallet บนอุปกรณ์นี้', walletTitle:'การตั้งค่ากระเป๋าส่วนตัว', walletText:'สกุลเงินของรายการมาจากยอดสกุลเงินในบัญชี ส่วนสกุลเงินรายงานใช้เฉพาะมุมมองแบบแปลงค่า', inputTitle:'การป้อนข้อมูลและระบบอัตโนมัติ', inputText:'กำหนดวิธีบันทึกรายการในชีวิตประจำวัน', syncTitle:'ซิงค์และความปลอดภัย', syncText:'จัดการ Google Drive, Quick Unlock, การจำสถานะเซสชัน การล็อก และการสลับบัญชี', dataTitle:'ข้อมูลและแอป', dataText:'นำเข้าหรือส่งออกข้อมูล ตรวจสอบพื้นที่จัดเก็บในเครื่อง และดูข้อมูลแอป',
    budgetTitle:'งบประมาณ / เป้าหมายการใช้จ่าย', budgetHint:'เป็นเป้าหมายติดตามรายเดือน ไม่ใช่วงเงินบังคับ เมื่อใช้เกินแล้ว O-Wallet ยังบันทึกรายการตามปกติ', reportingCurrency:'สกุลเงินสำหรับแปลง / รายงาน', reportingCurrencyHint:'ใช้เฉพาะ Dashboard, Analytics และงบประมาณในมุมมองแบบแปลงค่า รายการจะเก็บจำนวนเงินและสกุลเงินเดิมเสมอ', addBudget:'เพิ่มงบประมาณ', noBudgets:'ยังไม่มีงบประมาณ'
  },
  id: {
    general:'Umum', generalHint:'Tampilan dan perilaku aplikasi', wallet:'Dompet pribadi', walletHint:'Akun, saldo mata uang, dan kategori', input:'Input & AI', inputHint:'Suara, OCR, dan AI', sync:'Sinkronisasi & keamanan', syncHint:'Google Drive, Quick Unlock, dan penguncian', cloud:'Personal Cloud', cloudHint:'Cloudflare Worker milik Anda sendiri', data:'Data & aplikasi', dataHint:'Impor, ekspor, penyimpanan, dan info aplikasi',
    defaults:'Default', accounts:'Akun', categories:'Kategori', budgets:'Anggaran', rules:'Aturan', voice:'Suara', ocr:'OCR', ai:'AI',
    generalTitle:'Pengaturan umum', generalText:'Atur tampilan dan cara O-Wallet bekerja di perangkat ini.', walletTitle:'Pengaturan dompet pribadi', walletText:'Mata uang transaksi mengikuti saldo mata uang pada akun; mata uang pelaporan hanya digunakan untuk tampilan konversi.', inputTitle:'Input & otomatisasi', inputText:'Atur cara mencatat transaksi sehari-hari.', syncTitle:'Sinkronisasi & keamanan', syncText:'Kelola Google Drive, Quick Unlock, penyimpanan sesi, penguncian, dan pergantian akun.', dataTitle:'Data & aplikasi', dataText:'Impor atau ekspor data, periksa penyimpanan lokal, dan lihat informasi aplikasi.',
    budgetTitle:'Anggaran / target pengeluaran', budgetHint:'Ini adalah target pemantauan bulanan, bukan batas keras. O-Wallet tetap mencatat transaksi setelah target terlewati.', reportingCurrency:'Mata uang konversi / pelaporan', reportingCurrencyHint:'Hanya digunakan pada Dashboard, Analytics, dan anggaran dalam tampilan konversi. Transaksi selalu menyimpan jumlah dan mata uang aslinya.', addBudget:'Tambah anggaran', noBudgets:'Belum ada anggaran.'
  },
  es: {
    general:'General', generalHint:'Apariencia y funcionamiento de la app', wallet:'Cartera personal', walletHint:'Cuentas, saldos por moneda y categorías', input:'Entrada e IA', inputHint:'Voz, OCR e IA', sync:'Sincronización y seguridad', syncHint:'Google Drive, Quick Unlock y bloqueo', cloud:'Personal Cloud', cloudHint:'Tu propio Cloudflare Worker', data:'Datos y aplicación', dataHint:'Importación, exportación, almacenamiento e información',
    defaults:'Valores predeterminados', accounts:'Cuentas', categories:'Categorías', budgets:'Presupuestos', rules:'Reglas', voice:'Voz', ocr:'OCR', ai:'IA',
    generalTitle:'Ajustes generales', generalText:'Configura la apariencia y el comportamiento de O-Wallet en este dispositivo.', walletTitle:'Ajustes de la cartera personal', walletText:'La moneda de cada transacción viene del saldo por moneda de la cuenta; la moneda de informe solo se usa para vistas convertidas.', inputTitle:'Entrada y automatización', inputText:'Configura cómo registras tus transacciones diarias.', syncTitle:'Sincronización y seguridad', syncText:'Gestiona Google Drive, Quick Unlock, la sesión, el bloqueo y el cambio de cuenta.', dataTitle:'Datos y aplicación', dataText:'Importa o exporta datos, revisa el almacenamiento local y consulta la información de la aplicación.',
    budgetTitle:'Presupuesto / objetivo de gasto', budgetHint:'Es un objetivo mensual de seguimiento, no un límite estricto. O-Wallet seguirá registrando transacciones cuando lo superes.', reportingCurrency:'Moneda de conversión / informe', reportingCurrencyHint:'Solo se usa en Dashboard, Analytics y presupuestos cuando ves importes convertidos. Las transacciones conservan siempre su importe y moneda originales.', addBudget:'Añadir presupuesto', noBudgets:'Todavía no hay presupuestos.'
  },
  fr: {
    general:'Général', generalHint:'Apparence et comportement de l’application', wallet:'Portefeuille personnel', walletHint:'Comptes, soldes par devise et catégories', input:'Saisie et IA', inputHint:'Voix, OCR et IA', sync:'Synchronisation et sécurité', syncHint:'Google Drive, Quick Unlock et verrouillage', cloud:'Personal Cloud', cloudHint:'Votre propre Cloudflare Worker', data:'Données et application', dataHint:'Import, export, stockage et informations',
    defaults:'Valeurs par défaut', accounts:'Comptes', categories:'Catégories', budgets:'Budgets', rules:'Règles', voice:'Voix', ocr:'OCR', ai:'IA',
    generalTitle:'Paramètres généraux', generalText:'Réglez l’apparence et le comportement d’O-Wallet sur cet appareil.', walletTitle:'Paramètres du portefeuille personnel', walletText:'La devise d’une transaction vient du solde en devise du compte ; la devise de référence ne sert qu’aux vues converties.', inputTitle:'Saisie et automatisation', inputText:'Configurez la façon dont vous enregistrez vos transactions au quotidien.', syncTitle:'Synchronisation et sécurité', syncText:'Gérez Google Drive, Quick Unlock, la conservation de session, le verrouillage et le changement de compte.', dataTitle:'Données et application', dataText:'Importez ou exportez vos données, consultez le stockage local et les informations de l’application.',
    budgetTitle:'Budget / objectif de dépenses', budgetHint:'Il s’agit d’un objectif mensuel de suivi, pas d’une limite bloquante. O-Wallet continue d’enregistrer les transactions après dépassement.', reportingCurrency:'Devise de conversion / référence', reportingCurrencyHint:'Utilisée uniquement dans Dashboard, Analytics et les budgets en affichage converti. Les transactions conservent toujours leur montant et leur devise d’origine.', addBudget:'Ajouter un budget', noBudgets:'Aucun budget pour le moment.'
  },
  de: {
    general:'Allgemein', generalHint:'Darstellung und App-Verhalten', wallet:'Persönliche Finanzen', walletHint:'Konten, Währungssalden und Kategorien', input:'Eingabe & KI', inputHint:'Sprache, OCR und KI', sync:'Synchronisierung & Sicherheit', syncHint:'Google Drive, Quick Unlock und Sperre', cloud:'Personal Cloud', cloudHint:'Eigener Cloudflare Worker', data:'Daten & App', dataHint:'Import, Export, Speicher und App-Infos',
    defaults:'Standardwerte', accounts:'Konten', categories:'Kategorien', budgets:'Budgets', rules:'Regeln', voice:'Sprache', ocr:'OCR', ai:'KI',
    generalTitle:'Allgemeine Einstellungen', generalText:'Darstellung und Verhalten von O-Wallet auf diesem Gerät festlegen.', walletTitle:'Einstellungen für persönliche Finanzen', walletText:'Die Transaktionswährung ergibt sich aus dem Währungssaldo des Kontos; die Berichtswährung wird nur für umgerechnete Ansichten verwendet.', inputTitle:'Eingabe & Automatisierung', inputText:'Festlegen, wie alltägliche Transaktionen erfasst werden.', syncTitle:'Synchronisierung & Sicherheit', syncText:'Google Drive, Quick Unlock, Sitzungsspeicherung, Sperre und Kontowechsel verwalten.', dataTitle:'Daten & App', dataText:'Daten importieren oder exportieren, lokalen Speicher prüfen und App-Informationen anzeigen.',
    budgetTitle:'Budget / Ausgabenziel', budgetHint:'Dies ist ein monatliches Beobachtungsziel, kein hartes Ausgabenlimit. O-Wallet erfasst Transaktionen auch nach Überschreitung weiter.', reportingCurrency:'Umrechnungs- / Berichtswährung', reportingCurrencyHint:'Wird nur für umgerechnete Dashboard-, Analytics- und Budgetansichten verwendet. Transaktionen behalten immer Originalbetrag und -währung.', addBudget:'Budget hinzufügen', noBudgets:'Noch keine Budgets vorhanden.'
  },
  'pt-BR': {
    general:'Geral', generalHint:'Aparência e comportamento do app', wallet:'Carteira pessoal', walletHint:'Contas, saldos por moeda e categorias', input:'Entrada e IA', inputHint:'Voz, OCR e IA', sync:'Sincronização e segurança', syncHint:'Google Drive, Quick Unlock e bloqueio', cloud:'Personal Cloud', cloudHint:'Seu próprio Cloudflare Worker', data:'Dados e app', dataHint:'Importação, exportação, armazenamento e informações',
    defaults:'Padrões', accounts:'Contas', categories:'Categorias', budgets:'Orçamentos', rules:'Regras', voice:'Voz', ocr:'OCR', ai:'IA',
    generalTitle:'Configurações gerais', generalText:'Defina a aparência e o comportamento do O-Wallet neste dispositivo.', walletTitle:'Configurações da carteira pessoal', walletText:'A moeda da transação vem do saldo por moeda da conta; a moeda de relatório é usada apenas nas visualizações convertidas.', inputTitle:'Entrada e automação', inputText:'Configure como você registra as transações do dia a dia.', syncTitle:'Sincronização e segurança', syncText:'Gerencie Google Drive, Quick Unlock, retenção de sessão, bloqueio e troca de conta.', dataTitle:'Dados e app', dataText:'Importe ou exporte dados, confira o armazenamento local e veja informações do app.',
    budgetTitle:'Orçamento / meta de gastos', budgetHint:'É uma meta mensal de acompanhamento, não um limite rígido. O-Wallet continua registrando transações após o valor ser ultrapassado.', reportingCurrency:'Moeda de conversão / relatório', reportingCurrencyHint:'Usada apenas no Dashboard, Analytics e orçamentos em visualizações convertidas. As transações sempre mantêm o valor e a moeda originais.', addBudget:'Adicionar orçamento', noBudgets:'Ainda não há orçamentos.'
  },
  ru: {
    general:'Общие', generalHint:'Внешний вид и поведение приложения', wallet:'Личный кошелёк', walletHint:'Счета, валютные остатки и категории', input:'Ввод и ИИ', inputHint:'Голос, OCR и ИИ', sync:'Синхронизация и безопасность', syncHint:'Google Drive, Quick Unlock и блокировка', cloud:'Personal Cloud', cloudHint:'Ваш собственный Cloudflare Worker', data:'Данные и приложение', dataHint:'Импорт, экспорт, хранилище и сведения о приложении',
    defaults:'По умолчанию', accounts:'Счета', categories:'Категории', budgets:'Бюджеты', rules:'Правила', voice:'Голос', ocr:'OCR', ai:'ИИ',
    generalTitle:'Общие настройки', generalText:'Настройте внешний вид и поведение O-Wallet на этом устройстве.', walletTitle:'Настройки личного кошелька', walletText:'Валюта транзакции определяется валютным остатком счёта; отчётная валюта используется только для пересчитанных представлений.', inputTitle:'Ввод и автоматизация', inputText:'Настройте способы добавления повседневных транзакций.', syncTitle:'Синхронизация и безопасность', syncText:'Управляйте Google Drive, Quick Unlock, сохранением сеанса, блокировкой и сменой аккаунта.', dataTitle:'Данные и приложение', dataText:'Импортируйте и экспортируйте данные, проверяйте локальное хранилище и сведения о приложении.',
    budgetTitle:'Бюджет / цель расходов', budgetHint:'Это месячная цель для контроля, а не жёсткий лимит. O-Wallet продолжит записывать транзакции после её превышения.', reportingCurrency:'Валюта пересчёта / отчётов', reportingCurrencyHint:'Используется только в пересчитанных видах Dashboard, Analytics и бюджетов. Транзакции всегда сохраняют исходные сумму и валюту.', addBudget:'Добавить бюджет', noBudgets:'Бюджетов пока нет.'
  }
}

function downloadText(filename: string, text: string, mime = 'application/json') {
  const url = URL.createObjectURL(new Blob([text], { type: `${mime};charset=utf-8` }))
  const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url)
}
function csvCell(value: unknown) { const text = value == null ? '' : String(value); const safe = /^[=+@-]/.test(text.trimStart()) ? `'${text}` : text; return `"${safe.replaceAll('"', '""')}"` }

export function Settings() {
  const wallet = useWallet()
  const { settings, accounts, categories, transactions, repository, saveEntity, saveEntities, googleSession, googleBinding, googleRememberedUser, googleConnectionState, googleConfigured, devicePreferences, updateDevicePreferences, connectGoogle, retryGoogleConnection, disconnectGoogle, switchLocalAccount, syncNow, syncBusy, syncMessage, lastSync, lock, error } = wallet
  const { t, locale, uiLanguage, setLanguage } = useI18n()
  const L = COPY[uiLanguage]
  const [section, setSection] = useState<SettingsSection>('general')
  const [walletSection, setWalletSection] = useState<WalletSection>('defaults')
  const [inputSection, setInputSection] = useState<InputSection>('voice')
  const [storage, setStorage] = useState({ recordCount: 0, imageCount: 0, imageBytes: 0 })
  const [driveFolder, setDriveFolder] = useState<string>()
  const [budgetCategoryId, setBudgetCategoryId] = useState('')
  const [budgetLimit, setBudgetLimit] = useState('')
  const reportCurrency = (settings?.defaultCurrency ?? 'VND').trim().toUpperCase()
  const catalogues = settings?.accountCatalogues ?? []
  const budgets = settings?.budgets ?? []
  const templates = settings?.ocrTemplates ?? []
  const expenseCategories = selectableCategories(categories, 'expense')

  useEffect(() => { void repository?.storageStats().then(setStorage) }, [repository, transactions])
  useEffect(() => { if (!googleSession) { setDriveFolder(undefined); return }; void findExistingDriveLayout(googleSession.accessToken).then((layout) => setDriveFolder(layout?.rootId)).catch(() => setDriveFolder(undefined)) }, [googleSession, lastSync])

  async function updateSettings(patch: Partial<AppSettings>) { if (settings) await saveEntity({ ...settings, ...patch, updatedAt: new Date().toISOString() }) }
  async function changeLanguage(next: UiLanguage) { setLanguage(next); await updateSettings({ language: next as AppSettings['language'] }) }
  async function changeRemember(kind: 'google' | 'vault', value: RememberDuration | VaultRememberDuration) { const next = kind === 'google' ? { ...devicePreferences, googleRemember: value as RememberDuration } : { ...devicePreferences, vaultRemember: value as VaultRememberDuration }; await updateDevicePreferences(next); await updateSettings({ rememberDefaults: next }) }
  async function addBudget() { if (!settings || !budgetCategoryId || Number(budgetLimit) <= 0) return; const next: BudgetConfig = { id: crypto.randomUUID(), categoryId: budgetCategoryId, monthlyLimit: Number(budgetLimit) }; await updateSettings({ budgets: [...budgets.filter((item) => item.categoryId !== budgetCategoryId), next] }); setBudgetLimit('') }
  async function confirmSwitchAccount() { if (window.confirm(t('settings.switchAccountConfirm'))) await switchLocalAccount() }

  function exportJson() { downloadText(`o-wallet-export-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify({ exportedAt: new Date().toISOString(), version: 1, transactions, accounts, categories, settings }, null, 2)) }
  function exportCsv() {
    const header = ['id','type','amount','currency','destinationAmount','destinationCurrency','occurredAt','category','account','merchant','balanceAfter','description','note','tags','images']
    const categoryMap = new Map(categories.map((item) => [item.id, categoryPath(item, categories)])); const accountMap = new Map(accounts.map((item) => [item.id, accountDisplayName(item, t)]))
    const rows = transactions.map((tx) => [tx.id,tx.type,tx.amount,tx.currency,tx.destinationAmount ?? '',tx.destinationCurrency ?? '',tx.occurredAt,categoryMap.get(tx.categoryId) ?? t('categories.uncategorized'),accountMap.get(tx.accountId) ?? tx.accountId,tx.merchant ?? '',tx.balanceAfter ?? '',tx.description ?? '',tx.note ?? '',(tx.tags ?? []).join('|'),tx.imageIds.length].map(csvCell).join(','))
    downloadText(`o-wallet-transactions-${new Date().toISOString().slice(0,10)}.csv`, [header.map(csvCell).join(','), ...rows].join('\n'), 'text/csv')
  }

  const sections = [
    { id:'general' as const,label:L.general,hint:L.generalHint,icon:Settings2 },{ id:'wallet' as const,label:L.wallet,hint:L.walletHint,icon:WalletCards },{ id:'input' as const,label:L.input,hint:L.inputHint,icon:Sparkles },{ id:'sync' as const,label:L.sync,hint:L.syncHint,icon:ShieldCheck },{ id:'cloud' as const,label:L.cloud,hint:L.cloudHint,icon:Cloud },{ id:'data' as const,label:L.data,hint:L.dataHint,icon:Database },
  ]

  return <div className="space-y-5">
    <div><h1 className="text-2xl font-semibold tracking-tight text-stone-950 dark:text-white">{t('settings.title')}</h1><p className="mt-1 text-sm text-stone-500">{t('settings.subtitle')}</p></div>
    <div className="grid gap-5 lg:grid-cols-[230px_minmax(0,1fr)]">
      <aside className="min-w-0 lg:sticky lg:top-20 lg:self-start"><div className="flex gap-2 overflow-x-auto pb-1 lg:flex-col lg:overflow-visible">{sections.map((item) => <SectionButton key={item.id} active={section===item.id} label={item.label} hint={item.hint} icon={<item.icon size={18}/>} onClick={()=>setSection(item.id)}/>)}</div></aside>
      <div className="min-w-0">
        {section==='general' && <div className="space-y-5"><SectionHeading title={L.generalTitle} text={L.generalText}/><Card className="p-4 sm:p-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><div><Label>{t('common.language')}</Label><Select value={uiLanguage} onChange={(e)=>void changeLanguage(e.target.value as UiLanguage)}>{UI_LANGUAGES.map((item)=><option key={item.code} value={item.code}>{item.label}</option>)}</Select></div><div><Label>{t('settings.theme')}</Label><Select value={settings?.theme ?? 'system'} onChange={(e)=>void updateSettings({theme:e.target.value as ThemeMode})}><option value="system">{t('common.system')}</option><option value="light">{t('common.light')}</option><option value="dark">{t('common.dark')}</option></Select></div><div><Label>{t('settings.imageRetention')}</Label><Select value={settings?.imageRetention.mode ?? 'forever'} onChange={(e)=>void updateSettings({imageRetention:{mode:e.target.value as 'forever'|'days',days:settings?.imageRetention.days ?? 90}})}><option value="forever">{t('common.forever')}</option><option value="days">{t('common.days',{count:settings?.imageRetention.days ?? 90})}</option></Select></div>{settings?.imageRetention.mode==='days' && <div><Label>{t('settings.keepDays')}</Label><Input type="number" min="1" value={settings.imageRetention.days} onChange={(e)=>void updateSettings({imageRetention:{mode:'days',days:Math.max(1,Number(e.target.value)||1)}})}/></div>}</div></Card></div>}

        {section==='wallet' && <div className="space-y-5"><SectionHeading title={L.walletTitle} text={L.walletText}/><SubNav value={walletSection} onChange={(v)=>setWalletSection(v as WalletSection)} items={[[ 'defaults',L.defaults ],['accounts',L.accounts],['categories',L.categories],['budgets',L.budgets],['rules',L.rules]]}/>
          {walletSection==='defaults' && <Card className="p-4 sm:p-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><div><Label>{L.reportingCurrency}</Label><CurrencyPicker value={reportCurrency} onChange={(code)=>void updateSettings({defaultCurrency:code})} locale={locale}/><p className="mt-1 text-xs leading-5 text-stone-400">{L.reportingCurrencyHint}</p></div><div><Label>{t('settings.defaultAccount')}</Label><AccountSelect accounts={accounts} catalogues={catalogues} value={settings?.transactionDefaults?.accountId ?? ''} onChange={(value)=>void updateSettings({transactionDefaults:{...settings?.transactionDefaults,accountId:value||undefined}})} includeEmpty/></div><div><Label>{t('settings.defaultCategory')}</Label><CategoryPicker categories={categories} value={settings?.transactionDefaults?.categoryId ?? ''} onChange={(value)=>void updateSettings({transactionDefaults:{...settings?.transactionDefaults,categoryId:value||undefined}})} placeholder={t('common.none')}/></div></div></Card>}
          {walletSection==='accounts' && <AccountManager accounts={accounts} transactions={transactions} settings={settings} onSaveAccount={async(a)=>{await saveEntity(a)}} onSaveAccounts={async(items)=>{await saveEntities(items)}} onSaveSettings={updateSettings}/>} 
          {walletSection==='categories' && <CategoryManager categories={categories} transactions={transactions} onSave={async(c)=>{await saveEntity(c)}} onSaveMany={async(items)=>{await saveEntities(items)}}/>}
          {walletSection==='budgets' && <Card className="p-4 sm:p-5"><h2 className="font-bold">{L.budgetTitle}</h2><p className="mt-1 text-sm leading-6 text-stone-500">{L.budgetHint}</p><div className="mt-4 rounded-2xl border border-stone-200 bg-stone-50/60 p-3 dark:border-stone-800 dark:bg-stone-950/30"><div className="mb-3 text-sm font-semibold text-stone-800 dark:text-stone-200">{L.addBudget}</div><div className="grid gap-3 sm:grid-cols-[1fr_180px_auto]"><Select value={budgetCategoryId} onChange={(e)=>setBudgetCategoryId(e.target.value)}><option value="">{t('settings.chooseCategory')}</option>{expenseCategories.map((category)=><option key={category.id} value={category.id}>{categoryPath(category,categories)}</option>)}</Select><Input type="number" min="1" value={budgetLimit} onChange={(e)=>setBudgetLimit(e.target.value)} placeholder={t('settings.budgetLimit')}/><Button onClick={()=>void addBudget()}><Plus size={17}/>{t('common.add')}</Button></div></div><div className="mt-4 space-y-2">{budgets.length?budgets.map((budget)=>{const category=categories.find((item)=>item.id===budget.categoryId);return <div key={budget.id} className="flex items-center gap-3 rounded-xl border border-stone-200 p-3 dark:border-stone-800"><div className="min-w-0 flex-1"><div className="truncate font-bold">{category?categoryPath(category,categories):budget.categoryId}</div><div className="text-xs text-stone-500">{formatMoney(budget.monthlyLimit,reportCurrency,locale)} / {t('settings.month')}</div></div><Button variant="ghost" className="px-2 text-rose-500" onClick={()=>void updateSettings({budgets:budgets.filter((item)=>item.id!==budget.id)})}><Trash2 size={16}/></Button></div>}):<div className="rounded-xl border border-dashed border-stone-300 px-4 py-7 text-center text-sm text-stone-500 dark:border-stone-700">{L.noBudgets}</div>}</div></Card>}
          {walletSection==='rules' && <RuleManager settings={settings} categories={categories} accounts={accounts} onSaveSettings={updateSettings}/>} 
        </div>}

        {section==='input' && <div className="space-y-5"><SectionHeading title={L.inputTitle} text={L.inputText}/><SubNav value={inputSection} onChange={(v)=>setInputSection(v as InputSection)} items={[[ 'voice',L.voice ],['ocr',L.ocr],['ai',L.ai]]}/>{inputSection==='voice' && <VoiceSettings settings={settings} onSaveSettings={updateSettings}/>} {inputSection==='ocr' && <Card className="p-4 sm:p-5"><h2 className="font-bold">{t('settings.ocrTemplates')}</h2><p className="mt-1 text-sm text-stone-500">{t('settings.ocrTemplatesHint')}</p><div className="mt-4 space-y-2">{templates.length===0?<div className="rounded-xl bg-stone-50 p-3 text-sm text-stone-500 dark:bg-stone-950">{t('settings.noOcrTemplates')}</div>:templates.map((template)=><div key={template.id} className="flex items-center gap-3 rounded-xl border border-stone-200 p-3 dark:border-stone-800"><div className="min-w-0 flex-1"><div className="truncate font-bold">{template.name}</div><div className="text-xs text-stone-500">{t('settings.regionCount',{count:template.regions.length})}</div></div><Button variant="ghost" className="px-2 text-rose-500" onClick={()=>void updateSettings({ocrTemplates:templates.filter((item)=>item.id!==template.id)})}><Trash2 size={16}/></Button></div>)}</div></Card>} {inputSection==='ai' && <AiSettings settings={settings} repository={repository} onSaveSettings={updateSettings}/>}</div>}

        {section==='sync' && <div className="space-y-5"><SectionHeading title={L.syncTitle} text={L.syncText}/><DriveCard/><QuickUnlockSettings/><Card className="p-4 sm:p-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><div><Label>{t('settings.autoSync')}</Label><Select value={settings?.autoSync?'on':'off'} onChange={(e)=>void updateSettings({autoSync:e.target.value==='on'})}><option value="on">{t('common.on')}</option><option value="off">{t('common.off')}</option></Select></div><div><Label>{t('settings.googleRemember')}</Label><RememberSelect value={devicePreferences.googleRemember} onChange={(v)=>void changeRemember('google',v as RememberDuration)} google/></div><div><Label>{t('settings.vaultRemember')}</Label><RememberSelect value={devicePreferences.vaultRemember} onChange={(v)=>void changeRemember('vault',v as VaultRememberDuration)}/></div></div></Card><Card className="p-4 sm:p-5"><h2 className="font-bold">{t('settings.security')}</h2><p className="mt-1 text-sm text-stone-500">{t('settings.securityHint')}</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" onClick={lock}><LockKeyhole size={17}/>{t('settings.lockVault')}</Button><Button variant="danger" onClick={()=>void confirmSwitchAccount()}>{t('settings.switchAccount')}</Button></div></Card></div>}
        {section==='cloud' && <PersonalCloudSettings/>}
        {section==='data' && <div className="space-y-5"><SectionHeading title={L.dataTitle} text={L.dataText}/><ExternalImport/><Card className="p-4 sm:p-5"><h2 className="font-bold">{t('settings.export')}</h2><div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" onClick={exportJson}><Download size={16}/>JSON</Button><Button variant="secondary" onClick={exportCsv}><Download size={16}/>CSV</Button></div></Card><Card className="p-4 sm:p-5"><h2 className="font-bold">{t('settings.localStorage')}</h2><div className="mt-4 grid grid-cols-3 gap-3"><Metric label={t('settings.records')} value={String(storage.recordCount)}/><Metric label={t('settings.images')} value={String(storage.imageCount)}/><Metric label={t('settings.encryptedImageBytes')} value={bytesToHuman(storage.imageBytes)}/></div></Card><Card className="p-4 text-xs text-stone-500 sm:p-5"><div className="flex items-center gap-2 font-bold"><ExternalLink size={15}/>{t('settings.deploymentNote')}</div><div className="mt-3 flex gap-3"><a className="font-semibold text-blue-600" href="./privacy.html" target="_blank" rel="noreferrer">{t('settings.privacy')}</a><a className="font-semibold text-blue-600" href="./terms.html" target="_blank" rel="noreferrer">{t('settings.terms')}</a></div></Card></div>}
      </div>
    </div>
  </div>

  function DriveCard() {
    return <Card className="p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{t('settings.driveSync')}</h2><p className="mt-1 max-w-2xl text-sm text-stone-500">{t('settings.driveHint')}</p></div><Badge tone={googleConnectionState==='connected'?'green':googleConnectionState==='attention'?'red':googleConnectionState==='reconnecting'?'amber':undefined}>{t(`common.${googleConnectionState==='connected'?'connected':googleConnectionState==='reconnecting'?'reconnecting':googleConnectionState==='attention'?'actionRequired':'disconnected'}`)}</Badge></div>{!googleConfigured&&<div className="mt-4 rounded-xl bg-amber-50 px-3 py-2 text-sm text-amber-700">{t('settings.clientMissing')}</div>}{googleSession?<div className="mt-4 flex flex-wrap items-center gap-3">{safeGoogleProfileImageUrl(googleSession.user.picture)&&<img src={safeGoogleProfileImageUrl(googleSession.user.picture)} className="h-10 w-10 rounded-full" alt={t('settings.googleProfileAlt')}/>}<div className="mr-auto min-w-0"><div className="truncate text-sm font-bold">{googleSession.user.name}</div><div className="truncate text-xs text-stone-500">{googleSession.user.email}</div></div><Button variant="secondary" onClick={()=>void syncNow()} disabled={syncBusy}><RefreshCw className={syncBusy?'animate-spin':''} size={17}/>{syncBusy?syncMessage||t('common.syncing'):t('settings.syncNow')}</Button>{driveFolder&&<Button variant="secondary" onClick={()=>openTrustedExternalUrl(openDriveFolderUrl(driveFolder))}><FolderOpen size={17}/>{t('settings.openDrive')}</Button>}<Button variant="ghost" onClick={disconnectGoogle}><Unplug size={17}/>{t('settings.disconnect')}</Button></div>:(googleRememberedUser||googleBinding)?<div className="mt-4"><Button variant="secondary" onClick={()=>void retryGoogleConnection()} disabled={!googleConfigured||googleConnectionState==='reconnecting'}><RefreshCw size={17}/>{t('settings.reconnectGoogle')}</Button></div>:<div className="mt-4"><Button onClick={()=>void connectGoogle()} disabled={!googleConfigured}><Cloud size={17}/>{t('settings.connectGoogle')}</Button></div>}{lastSync&&<div className="mt-3 text-xs text-stone-500">{t('settings.lastSync',{pulledRecords:lastSync.pulledRecords,pulledImages:lastSync.pulledImages,pushedRecords:lastSync.pushedRecords,pushedImages:lastSync.pushedImages,conflicts:lastSync.conflictsResolved})}</div>}{error&&<div className="mt-3 text-sm text-rose-600">{error}</div>}</Card>
  }

  function RememberSelect({value,onChange,google=false}:{value:string;onChange:(value:string)=>void;google?:boolean}) { return <Select value={value} onChange={(e)=>onChange(e.target.value)}>{google&&<option value="tab">{t('settings.googleRememberTab')}</option>}<option value="off">{google?t('settings.googleRememberOff'):t('settings.vaultRememberOff')}</option>{!google&&<option value="15m">{t('settings.duration15m')}</option>}<option value="1h">{t('settings.duration1h')}</option><option value="8h">{t('settings.duration8h')}</option><option value="1d">{t('settings.duration1d')}</option><option value="7d">{t('settings.duration7d')}</option><option value="30d">{t('settings.duration30d')}</option></Select> }
}

function SectionButton({active,label,hint,icon,onClick}:{active:boolean;label:string;hint:string;icon:ReactNode;onClick:()=>void}) { return <button type="button" onClick={onClick} className={`flex shrink-0 items-center gap-3 rounded-xl border px-3 py-3 text-left transition lg:w-full ${active?'border-stone-300 bg-white text-stone-950 shadow-sm dark:border-stone-700 dark:bg-stone-900 dark:text-white':'border-transparent text-stone-500 hover:bg-white/70 dark:hover:bg-stone-900/70'}`}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-stone-100 dark:bg-stone-900">{icon}</span><span><span className="block whitespace-nowrap text-sm font-semibold">{label}</span><span className="mt-0.5 hidden text-[11px] text-stone-400 lg:block">{hint}</span></span></button> }
function SectionHeading({title,text}:{title:string;text:string}) { return <div><h2 className="text-lg font-semibold tracking-tight text-stone-950 dark:text-white">{title}</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-stone-500">{text}</p></div> }
function SubNav({value,onChange,items}:{value:string;onChange:(value:string)=>void;items:Array<readonly [string,string]>}) { return <div className="flex gap-1 overflow-x-auto rounded-xl border border-stone-200 bg-white p-1 dark:border-stone-800 dark:bg-stone-950">{items.map(([id,label])=><button key={id} type="button" onClick={()=>onChange(id)} className={`shrink-0 rounded-lg px-3 py-2 text-sm font-semibold ${value===id?'bg-stone-950 text-white dark:bg-white dark:text-stone-950':'text-stone-500 hover:bg-stone-100 dark:hover:bg-stone-900'}`}>{label}</button>)}</div> }
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-xl bg-stone-50 p-3 dark:bg-stone-950"><div className="text-xs text-stone-500">{label}</div><div className="mt-1 font-semibold">{value}</div></div> }
